### ISSUE TITLE
issue with data in V06B

### ISSUE THREAD

**Issue by paolap** [aus-ref-clim-data-nci/GPM#3]
A user notify of an issue with data in V06B:

"I have been using the GPM data as part of the ia39 project and found an issue with one particular file:
/g/data/ia39/aus-ref-clim-data-nci/gpm/data/V06B/2017/3B-HHR.MS.MRG.3IMERG.V06B_20170222.nc
 
This file seems to be identical to the file of Feb 23 (i.e., /g/data/ia39/aus-ref-clim-data-nci/gpm/data/V06B/2017/3B-HHR.MS.MRG.3IMERG.V06B_20170223.nc)
 
I noticed because the time stamp in the file for Feb 22 is for the 23rd."

**Comment by greensh16** [comment]
For some reason 3B-HHR.MS.MRG.3IMERG.V06B_20170222.nc was a copy of 3B-HHR.MS.MRG.3IMERG.V06B_20170223.nc. This has now been fixed, I redownloaded and concatenated 3B-HHR.MS.MRG.3IMERG.V06B_20170222.nc.
