### ISSUE TITLE
IMERGv7 errors and missing files

### ISSUE THREAD

**Issue by joaquin-unsw** [aus-ref-clim-data-nci/GPM#6]
/g/data/ia39/aus-ref-clim-data-nci/gpm/data/V07/

I could read and work with the IMERGv7 data from years 2001-2014 without problem, but I am encountering an issue on year 2000 (data avail from June)
"ValueError: Coordinate variable time is neither monotonically increasing nor monotonically decreasing on all datasets"

Reading month by month I find no issues for months 06-07-08, but the error above for months 09 through 12 .

Can this be checked? maybe some issue while processing cdo/nco to generate these files.

Also, when looking for potential file duplications, I find that month 12 has 29 files instead of 31.

Thanks
Joaquin

Code used:

files = glob.glob(DIR_MAIN+str(year)+'/ *.nc')
files = glob.glob(DIR_MAIN+str(year)+'/'+file+month+' *.nc')
len (files)
data = xr.open_mfdataset(files,combine='by_coords',compat='override',coords='minimal',parallel=True).sel(lat=lat_range)

**Comment by paolap** [comment]
thanks for letting us know, @greensh16 let me know if you can check this, otherwise I will fix it myself, thanks

**Comment by greensh16** [comment]
Ok I'll have a look at this, maybe there's a corrupted file that messed up the concatenation for this months.

**Comment by greensh16** [comment]
@joaquin-unsw 09-12 for 2000 should work now, I used your code above and that data opens fine for me.

Let us know if you have any other issues with this dataset.

**Comment by joaquin-unsw** [comment]
excellent, issue solved, thanks !
